name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT: ci
      PORT: 4000
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 📥 Download deps
        run: npm ci --legacy-peer-deps

      - name: 🧪 Run test script
        run: npm test
